/* Generated by Purgatory 2014-2016 */

package ddbt.lib.store.deep

import ch.epfl.data.sc.pardis
import pardis.ir._
import pardis.types.PardisTypeImplicits._
import pardis.effects._
import pardis.deep._
import pardis.deep.scalalib._
import pardis.deep.scalalib.collection._
import pardis.deep.scalalib.io._

trait StringExtraOps extends Base  {  
  // Type representation
  val StringExtraType = StringExtraIRs.StringExtraType
  implicit val typeStringExtra: TypeRep[StringExtra] = StringExtraType
  implicit class StringExtraRep(self : Rep[StringExtra]) {

  }
  object StringExtra {
     def StringCompare(str1 : Rep[String], str2 : Rep[String]) : Rep[Int] = stringExtraStringCompareObject(str1, str2)
     def StringPrintf(maxSize : Rep[Int], f : Rep[String], args : Rep[Any]*) : Rep[String] = stringExtraStringPrintfObject(maxSize, f, args:_*)
  }
  // constructors

  // IR defs
  val StringExtraStringCompareObject = StringExtraIRs.StringExtraStringCompareObject
  type StringExtraStringCompareObject = StringExtraIRs.StringExtraStringCompareObject
  val StringExtraStringPrintfObject = StringExtraIRs.StringExtraStringPrintfObject
  type StringExtraStringPrintfObject = StringExtraIRs.StringExtraStringPrintfObject
  // method definitions
   def stringExtraStringCompareObject(str1 : Rep[String], str2 : Rep[String]) : Rep[Int] = StringExtraStringCompareObject(str1, str2)
   def stringExtraStringPrintfObject(maxSize : Rep[Int], f : Rep[String], args : Rep[Any]*) : Rep[String] = {
    val argsOutput = __liftSeq(args.toSeq)
    StringExtraStringPrintfObject(maxSize, f, argsOutput)
  }
  type StringExtra = ddbt.lib.store.StringExtra
}
object StringExtraIRs extends Base {
  // Type representation
  case object StringExtraType extends TypeRep[StringExtra] {
    def rebuild(newArguments: TypeRep[_]*): TypeRep[_] = StringExtraType
    val name = "StringExtra"
    val typeArguments = Nil
  }
      implicit val typeStringExtra: TypeRep[StringExtra] = StringExtraType
  // case classes
  case class StringExtraStringCompareObject(str1 : Rep[String], str2 : Rep[String]) extends FunctionDef[Int](None, "StringExtra.StringCompare", List(List(str1,str2))){
    override def curriedConstructor = (copy _).curried
    override def isPure = true

    override def partiallyEvaluate(children: Any*): Int = {
      val str1 = children(0).asInstanceOf[String]
      val str2 = children(1).asInstanceOf[String]
      ddbt.lib.store.StringExtra.StringCompare(str1, str2)
    }
    override def partiallyEvaluable: Boolean = true

  }

  case class StringExtraStringPrintfObject(maxSize : Rep[Int], f : Rep[String], argsOutput : Rep[Seq[Any]]) extends FunctionDef[String](None, "StringExtra.StringPrintf", List(List(maxSize,f,__varArg(argsOutput)))){
    override def curriedConstructor = (copy _).curried
  }

  type StringExtra = ddbt.lib.store.StringExtra
}
trait StringExtraImplicits extends StringExtraOps { 
  // Add implicit conversions here!
}
trait StringExtraComponent extends StringExtraOps with StringExtraImplicits {  }

trait StringExtraPartialEvaluation extends StringExtraComponent with BasePartialEvaluation {  
  // Immutable field inlining 

  // Mutable field inlining 
  // Pure function partial evaluation
}


