/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Vec3 */

#ifndef _Included_Vec3
#define _Included_Vec3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Vec3
 * Method:    dot
 * Signature: (LVec3;)LVec3;
 */
JNIEXPORT jobject JNICALL Java_Vec3_dot
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
